### ISSUE TITLE
Won't let me rename my user

### ISSUE THREAD

**Issue by aldrichdev** [aldrichdev/neatf2p-nextjs#107]
Reported by i3l4ck de4th: 
 
 Hi Team,
Trying to rename my username to have capital letters at the start of each word, but when I do it, nothing happens. No error message or anything.
Currently it is:  i3l4ck de4th
But I want it to be:  I3l4ck De4th
Can you please update it for me?
Thanks,
Sean

**Comment by BeastFable** [comment]
Good report! I will fix this soon. For now your account has been renamed.

**Comment by aldrichdev** [comment]
This is fixed with the latest website patch made on June 15th: https://www.neatf2p.com/news/post/45

Closing.
